package edu.ndsu.eci.capstone_exchange_sponsors.persist.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import edu.ndsu.eci.capstone_exchange_sponsors.persist.Application;
import edu.ndsu.eci.capstone_exchange_sponsors.persist.ApplicationNote;

/**
 * Class _ApplicationDate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ApplicationDate extends CayenneDataObject {

    public static final String END_DATE_PROPERTY = "endDate";
    public static final String START_DATE_PROPERTY = "startDate";
    public static final String APPLICATION_PROPERTY = "application";
    public static final String NOTE_PROPERTY = "note";

    public static final String PK_PK_COLUMN = "pk";

    public void setEndDate(Date endDate) {
        writeProperty("endDate", endDate);
    }
    public Date getEndDate() {
        return (Date)readProperty("endDate");
    }

    public void setStartDate(Date startDate) {
        writeProperty("startDate", startDate);
    }
    public Date getStartDate() {
        return (Date)readProperty("startDate");
    }

    public void setApplication(Application application) {
        setToOneTarget("application", application, true);
    }

    public Application getApplication() {
        return (Application)readProperty("application");
    }


    public void setNote(ApplicationNote note) {
        setToOneTarget("note", note, true);
    }

    public ApplicationNote getNote() {
        return (ApplicationNote)readProperty("note");
    }


}
