package edu.ndsu.eci.capstone_exchange_sponsors.persist.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import edu.ndsu.eci.capstone_exchange_sponsors.persist.Application;
import edu.ndsu.eci.capstone_exchange_sponsors.persist.ApplicationDate;
import edu.ndsu.eci.capstone_exchange_sponsors.persist.User;

/**
 * Class _ApplicationNote was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ApplicationNote extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String NOTE_PROPERTY = "note";
    public static final String APPLICATION_PROPERTY = "application";
    public static final String DATE_PROPERTY = "date";
    public static final String USER_PROPERTY = "user";

    public static final String PK_PK_COLUMN = "pk";

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setApplication(Application application) {
        setToOneTarget("application", application, true);
    }

    public Application getApplication() {
        return (Application)readProperty("application");
    }


    public void setDate(ApplicationDate date) {
        setToOneTarget("date", date, true);
    }

    public ApplicationDate getDate() {
        return (ApplicationDate)readProperty("date");
    }


    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


}
