package edu.ndsu.eci.capstone_exchange_sponsors.persist.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import edu.ndsu.eci.capstone_exchange_sponsors.persist.Site;
import edu.ndsu.eci.capstone_exchange_sponsors.util.enums.Status;

/**
 * Class _Country was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Country extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String ISO_A2_PROPERTY = "isoA2";
    public static final String NAME_PROPERTY = "name";
    public static final String SRC_PK_PROPERTY = "srcPk";
    public static final String STATUS_PROPERTY = "status";
    public static final String SITES_PROPERTY = "sites";

    public static final String PK_PK_COLUMN = "pk";

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setIsoA2(String isoA2) {
        writeProperty("isoA2", isoA2);
    }
    public String getIsoA2() {
        return (String)readProperty("isoA2");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSrcPk(Integer srcPk) {
        writeProperty("srcPk", srcPk);
    }
    public Integer getSrcPk() {
        return (Integer)readProperty("srcPk");
    }

    public void setStatus(Status status) {
        writeProperty("status", status);
    }
    public Status getStatus() {
        return (Status)readProperty("status");
    }

    public void addToSites(Site obj) {
        addToManyTarget("sites", obj, true);
    }
    public void removeFromSites(Site obj) {
        removeToManyTarget("sites", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Site> getSites() {
        return (List<Site>)readProperty("sites");
    }


}
