package edu.ndsu.eci.capstone_exchange_sponsors.persist.auto;

import org.apache.cayenne.CayenneDataObject;

import edu.ndsu.eci.capstone_exchange_sponsors.persist.User;
import edu.ndsu.eci.capstone_exchange_sponsors.util.Payment;

/**
 * Class _Sponsorship was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Sponsorship extends CayenneDataObject {

    public static final String COMPANY_PROPERTY = "company";
    public static final String EMAIL_PROPERTY = "email";
    public static final String PAYMENT_PROPERTY = "payment";
    public static final String USER_PROPERTY = "user";

    public static final String PK_PK_COLUMN = "pk";

    public void setCompany(String company) {
        writeProperty("company", company);
    }
    public String getCompany() {
        return (String)readProperty("company");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setPayment(Payment payment) {
        writeProperty("payment", payment);
    }
    public Payment getPayment() {
        return (Payment)readProperty("payment");
    }

    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


}
