package edu.ndsu.eci.capstone_exchange_sponsors.persist.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import edu.ndsu.eci.capstone_exchange_sponsors.persist.Role;
import edu.ndsu.eci.capstone_exchange_sponsors.persist.Site;
import edu.ndsu.eci.capstone_exchange_sponsors.util.enums.Status;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String EMAIL_PROPERTY = "email";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String SOURCE_PROPERTY = "source";
    public static final String SSO_EMAIL_PROPERTY = "ssoEmail";
    public static final String SSO_NAME_PROPERTY = "ssoName";
    public static final String STATUS_PROPERTY = "status";
    public static final String URL_PROPERTY = "url";
    public static final String WORK_PHONE_PROPERTY = "workPhone";
    public static final String ROLES_PROPERTY = "roles";
    public static final String SITE_PROPERTY = "site";

    public static final String PK_PK_COLUMN = "pk";

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSource(String source) {
        writeProperty("source", source);
    }
    public String getSource() {
        return (String)readProperty("source");
    }

    public void setSsoEmail(String ssoEmail) {
        writeProperty("ssoEmail", ssoEmail);
    }
    public String getSsoEmail() {
        return (String)readProperty("ssoEmail");
    }

    public void setSsoName(String ssoName) {
        writeProperty("ssoName", ssoName);
    }
    public String getSsoName() {
        return (String)readProperty("ssoName");
    }

    public void setStatus(Status status) {
        writeProperty("status", status);
    }
    public Status getStatus() {
        return (Status)readProperty("status");
    }

    public void setUrl(String url) {
        writeProperty("url", url);
    }
    public String getUrl() {
        return (String)readProperty("url");
    }

    public void setWorkPhone(String workPhone) {
        writeProperty("workPhone", workPhone);
    }
    public String getWorkPhone() {
        return (String)readProperty("workPhone");
    }

    public void addToRoles(Role obj) {
        addToManyTarget("roles", obj, true);
    }
    public void removeFromRoles(Role obj) {
        removeToManyTarget("roles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Role> getRoles() {
        return (List<Role>)readProperty("roles");
    }


    public void setSite(Site site) {
        setToOneTarget("site", site, true);
    }

    public Site getSite() {
        return (Site)readProperty("site");
    }


}
